#!/usr/bin/env bash
# Shared utilities for paper server setup scripts.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
KITS_DIR="${ROOT_DIR}/kits"
SERVERS_DIR="${ROOT_DIR}/servers"
SHARED_DIR="${KITS_DIR}/_shared"
PID_DIR="${SERVERS_DIR}/.pids"

log_info()  { printf '\033[1;34m[INFO]\033[0m %s\n' "$*"; }
log_warn()  { printf '\033[1;33m[WARN]\033[0m %s\n' "$*"; }
log_error() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; }
log_ok()    { printf '\033[1;32m[OK]\033[0m %s\n' "$*"; }

die() {
  log_error "$@"
  exit 1
}

require_cmd() {
  local cmd="$1"
  command -v "$cmd" >/dev/null 2>&1 || die "Required command not found: $cmd"
}

require_java() {
  local min_major="${1:-21}"
  require_cmd java
  local version_line
  version_line="$(java -version 2>&1 | head -n1)"
  local major
  major="$(echo "$version_line" | sed -n 's/.*version "\([0-9]*\).*/\1/p')"
  if [[ -z "$major" ]]; then
    major="$(echo "$version_line" | sed -n 's/.*version "1\.\([0-9]*\).*/\1/p')"
  fi
  [[ -n "$major" && "$major" -ge "$min_major" ]] || \
    die "Java ${min_major}+ required for this Minecraft version (found: ${version_line})"
}

# Minecraft 2026+ drop versioning: 26.1, 26.1.1, 26.1.2 (year.drop.patch)
# Legacy versioning: 1.21.11, 1.21.1, etc.
is_drop_version() {
  [[ "${1:-}" =~ ^[0-9]{2}\.[0-9] ]]
}

required_java_for_mc() {
  local mc_version="$1"
  if is_drop_version "$mc_version"; then
    echo 25
  else
    echo 21
  fi
}

papermc_project_versions() {
  local project="${1:-paper}"
  curl -fsSL "https://api.papermc.io/v2/projects/${project}"
}

latest_stable_paper_version() {
  papermc_project_versions paper | \
    jq -r '[.versions[] | select(test("pre|rc|snapshot"; "i") | not)] | .[-1]'
}

resolve_mc_version() {
  local requested="${MC_VERSION:-latest}"

  if [[ "$requested" == "latest" || -z "$requested" ]]; then
    MC_VERSION="$(latest_stable_paper_version)"
    log_info "Using latest Paper version: ${MC_VERSION}"
    return 0
  fi

  local versions_json
  versions_json="$(papermc_project_versions paper)"

  if echo "$versions_json" | jq -e --arg v "$requested" '.versions | index($v)' >/dev/null; then
    MC_VERSION="$requested"
    return 0
  fi

  local latest drop_versions legacy_versions
  latest="$(echo "$versions_json" | jq -r '[.versions[] | select(test("pre|rc|snapshot"; "i") | not)] | .[-1]')"
  drop_versions="$(echo "$versions_json" | jq -r '[.versions[] | select(test("^[0-9]{2}\\."))] | join(", ")')"
  legacy_versions="$(echo "$versions_json" | jq -r '[.versions[] | select(test("pre|rc|snapshot"; "i") | not)] | .[-5:] | join(", ")')"

  log_error "Minecraft version '${requested}' is not available from PaperMC yet."
  echo "" >&2
  if is_drop_version "$requested"; then
    echo "  '${requested}' uses the new drop versioning scheme (YY.DROP.PATCH)." >&2
    echo "  Example: 26.1 = first 2026 drop, 26.1.2 = second hotfix." >&2
    if [[ -z "$drop_versions" || "$drop_versions" == "null" ]]; then
      echo "  No drop versions (26.x) are published on PaperMC yet." >&2
      echo "  Use MC_VERSION=latest (currently ${latest}) until Paper ships ${requested}." >&2
    else
      echo "  Available drop versions: ${drop_versions}" >&2
    fi
  else
    echo "  Recent legacy versions (1.x): ${legacy_versions}" >&2
  fi
  echo "" >&2
  echo "  Set MC_VERSION=latest in .env or run: ./setup.sh <kit> --mc-version latest" >&2
  exit 1
}

require_java_for_mc() {
  require_java "$(required_java_for_mc "$1")"
}

ensure_env_file() {
  local env_file="${ROOT_DIR}/.env"
  local example="${ROOT_DIR}/.env.example"

  if [[ -f "$env_file" ]]; then
    return 0
  fi

  if [[ -f "$example" ]]; then
    grep -v '^#' "$example" | sed '/^[[:space:]]*$/d' > "$env_file"
  else
    cat > "$env_file" <<'EOF'
MC_VERSION=latest
VELOCITY_VERSION=
MEMORY=2G
CONSOLE_MODE=tmux
EOF
  fi
  log_info "Created ${env_file}"
}

save_env_file() {
  local env_file="${ROOT_DIR}/.env"
  cat > "$env_file" <<EOF
# Auto-generated by setup.sh — edit to change defaults for future runs
MC_VERSION=${MC_VERSION}
VELOCITY_VERSION=${VELOCITY_VERSION:-}
MEMORY=${MEMORY}
CONSOLE_MODE=${CONSOLE_MODE:-tmux}
EOF
}

load_env() {
  ensure_env_file
  if [[ -f "${ROOT_DIR}/.env" ]]; then
    # shellcheck disable=SC1091
    set -a
    source "${ROOT_DIR}/.env"
    set +a
  fi
  MC_VERSION="${MC_VERSION:-latest}"
  VELOCITY_VERSION="${VELOCITY_VERSION:-}"
  MEMORY="${MEMORY:-2G}"
  CONSOLE_MODE="${CONSOLE_MODE:-tmux}"
}

yaml_to_json() {
  local file="$1"
  if command -v ruby >/dev/null 2>&1; then
    ruby -ryaml -rjson -e 'puts JSON.generate(YAML.load_file(ARGV[0]))' "$file" 2>/dev/null
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c 'import json,sys; import yaml' 2>/dev/null && \
      python3 -c 'import json,sys,yaml; print(json.dumps(yaml.safe_load(open(sys.argv[1]))))' "$file" || \
      die "Install ruby or python3 with PyYAML to parse kit manifests"
  else
    die "Install ruby or python3 to parse kit manifests"
  fi
}

discover_kits() {
  local kit
  for kit_dir in "${KITS_DIR}"/*/; do
    kit="$(basename "$kit_dir")"
    [[ "$kit" == "_shared" ]] && continue
    [[ -f "${kit_dir}/kit.yml" ]] && echo "$kit"
  done | sort
}

kit_manifest_json() {
  local kit_id="$1"
  local manifest="${KITS_DIR}/${kit_id}/kit.yml"
  [[ -f "$manifest" ]] || die "Kit manifest not found: $manifest"
  yaml_to_json "$manifest"
}

kit_field() {
  local kit_id="$1"
  local field="$2"
  kit_manifest_json "$kit_id" | jq -r ".$field"
}

kit_servers() {
  local kit_id="$1"
  kit_manifest_json "$kit_id" | jq -c '.servers[]'
}

server_dir() {
  local kit_id="$1"
  local server_id="$2"
  echo "${SERVERS_DIR}/${kit_id}/${server_id}"
}

ensure_dir() {
  mkdir -p "$1"
}

generate_forwarding_secret() {
  local secret_file="${SERVERS_DIR}/.forwarding.secret"
  if [[ -f "$secret_file" ]]; then
    cat "$secret_file"
    return
  fi
  require_cmd openssl
  local secret
  secret="$(openssl rand -hex 16)"
  ensure_dir "$(dirname "$secret_file")"
  echo "$secret" > "$secret_file"
  echo "$secret"
}

render_luckperms_template() {
  local template="$1"
  local dest="$2"
  local server_name="$3"
  local db_path="${4:-}"
  sed -e "s|{{SERVER_NAME}}|${server_name}|g" \
      -e "s|{{LP_DB_PATH}}|${db_path}|g" \
      "$template" > "$dest"
}

configure_luckperms() {
  local kit_id="$1"
  local server_id="$2"
  local server_type="$3"
  local network_sync="$4"
  local sdir
  sdir="$(server_dir "$kit_id" "$server_id")"
  local config_dir="${sdir}/plugins/LuckPerms"
  local config_file="${config_dir}/config.yml"

  [[ -d "${sdir}/plugins" ]] || return 0

  ensure_dir "$config_dir"

  if [[ "$network_sync" == "true" ]]; then
    local db_dir="${SERVERS_DIR}/${kit_id}/.luckperms"
    local db_path="${db_dir}/luckperms"
    ensure_dir "$db_dir"
    render_luckperms_template \
      "${SHARED_DIR}/plugin-configs/LuckPerms/config-network.yml.template" \
      "$config_file" \
      "$server_id" \
      "$db_path"
    log_info "LuckPerms network sync enabled for ${server_id} (shared DB + pluginmsg)"
  else
    render_luckperms_template \
      "${SHARED_DIR}/plugin-configs/LuckPerms/config-standalone.yml.template" \
      "$config_file" \
      "$server_id"
    log_info "LuckPerms standalone config for ${server_id}"
  fi
}


render_template() {
  local src="$1"
  local dest="$2"
  local secret="${3:-}"
  local port="${4:-}"
  local server_port="${5:-}"
  sed -e "s|{{FORWARDING_SECRET}}|${secret}|g" \
      -e "s|{{PORT}}|${port}|g" \
      -e "s|{{SERVER_PORT}}|${server_port}|g" \
      "$src" > "$dest"
}

wait_for_server_ready() {
  local log_file="$1"
  local timeout="${2:-180}"
  local elapsed=0
  while [[ $elapsed -lt $timeout ]]; do
    if [[ -f "$log_file" ]] && grep -q "Done (" "$log_file" 2>/dev/null; then
      return 0
    fi
    sleep 2
    elapsed=$((elapsed + 2))
  done
  log_warn "Timed out waiting for server ready: $log_file"
  return 1
}
