#!/usr/bin/env bash
# Apply kit templates and wire Velocity forwarding.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/common.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/download-servers.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/install-plugins.sh"

build_velocity_servers_toml() {
  local kit_id="$1"
  local default_server="$2"
  local output="$3"
  local secret
  secret="$(generate_forwarding_secret)"

  {
    echo "# Auto-generated by apply-kit.sh"
    echo "config-version = \"2.7\""
    echo "bind = \"0.0.0.0:25565\""
    echo "motd = \"<#09add3>A Minecraft Server</#09add3>\""
    echo "show-max-players = 100"
    echo "online-mode = true"
    echo "force-key-authentication = true"
    echo "prevent-client-proxy-connections = false"
    echo "player-info-forwarding-mode = \"modern\""
    echo "forwarding-secret-file = \"forwarding.secret\""
    echo "announce-forge = false"
    echo "kick-existing-players = false"
    echo "ping-passthrough = \"DISABLED\""
    echo "enable-player-address-logging = true"
    echo ""
    echo "[servers]"
  } > "$output"

  local server_json
  while IFS= read -r server_json; do
    local sid stype sport
    sid="$(echo "$server_json" | jq -r '.id')"
    stype="$(echo "$server_json" | jq -r '.type')"
    sport="$(echo "$server_json" | jq -r '.port')"
    [[ "$stype" == "paper" ]] || continue
    echo "${sid} = \"127.0.0.1:${sport}\"" >> "$output"
  done < <(kit_servers "$kit_id")

  {
    echo ""
    echo "try = ["
    echo "    \"${default_server}\""
    echo "]"
    echo ""
    echo "[forced-hosts]"
    echo ""
    echo "[advanced]"
    echo "compression-threshold = 256"
    echo "compression-level = -1"
    echo "login-ratelimit = 3000"
    echo "connection-timeout = 5000"
    echo "read-timeout = 30000"
    echo "haproxy-protocol = false"
    echo "tcp-fast-open = false"
    echo "bungee-plugin-message-channel = true"
    echo "show-ping-requests = false"
    echo "failover-on-unexpected-server-disconnect = true"
    echo "announce-proxy-command = false"
    echo "log-command-executions = false"
    echo "log-player-connections = true"
    echo "accepts-transfers = false"
    echo ""
    echo "[query]"
    echo "enabled = false"
    echo "port = 25565"
    echo "map = \"Velocity\""
    echo "show-plugins = false"
  } >> "$output"

  echo "$secret"
}

apply_kit() {
  local kit_id="$1"
  local kit_dir="${KITS_DIR}/${kit_id}"
  local manifest_json
  manifest_json="$(kit_manifest_json "$kit_id")"

  local has_velocity=false
  local has_paper=false
  local forwarding_secret=""
  local default_server=""

  local server_json
  while IFS= read -r server_json; do
    local stype
    stype="$(echo "$server_json" | jq -r '.type')"
    [[ "$stype" == "velocity" ]] && has_velocity=true
    [[ "$stype" == "paper" ]] && has_paper=true
  done < <(kit_servers "$kit_id")

  if $has_velocity && $has_paper; then
    default_server="$(echo "$manifest_json" | jq -r '.default_server // "paper-lobby"')"
    local velocity_template="${kit_dir}/templates/velocity/velocity.toml.template"
    local velocity_dir
    velocity_dir="$(server_dir "$kit_id" "velocity")"
    ensure_dir "$velocity_dir"
    forwarding_secret="$(build_velocity_servers_toml "$kit_id" "$default_server" "${velocity_dir}/velocity.toml")"
    echo "$forwarding_secret" > "${velocity_dir}/forwarding.secret"
  elif $has_velocity; then
    local velocity_dir
    velocity_dir="$(server_dir "$kit_id" "velocity")"
    ensure_dir "$velocity_dir"
    if [[ -f "${kit_dir}/templates/velocity/velocity.toml" ]]; then
      cp "${kit_dir}/templates/velocity/velocity.toml" "${velocity_dir}/velocity.toml"
    fi
  fi

  while IFS= read -r server_json; do
    local sid stype sport sdir template_dir
    sid="$(echo "$server_json" | jq -r '.id')"
    stype="$(echo "$server_json" | jq -r '.type')"
    sport="$(echo "$server_json" | jq -r '.port')"
    sdir="$(server_dir "$kit_id" "$sid")"
    template_dir="${kit_dir}/templates/${sid}"

    log_info "Setting up server: ${sid} (${stype})"
    ensure_dir "$sdir"

    download_server_jar "$stype" "$sdir"

    local bundle
    bundle="$(echo "$manifest_json" | jq -r ".plugin_bundles.${stype} // empty")"
    if [[ -n "$bundle" ]]; then
      install_plugins_for_type "$bundle" "$sdir"
    fi

    if ls "${sdir}"/plugins/LuckPerms*.jar >/dev/null 2>&1; then
      configure_luckperms "$kit_id" "$sid" "$stype" "$($has_velocity && echo true || echo false)"
    fi

    if [[ -d "$template_dir" ]]; then
      while IFS= read -r -d '' f; do
        local rel dest_path basename_f
        rel="${f#"${template_dir}/"}"
        dest_path="${sdir}/${rel}"
        basename_f="$(basename "$f")"
        ensure_dir "$(dirname "$dest_path")"
        if [[ "$basename_f" == *.template ]]; then
          dest_path="${dest_path%.template}"
          if [[ "$stype" == "paper" && "$forwarding_secret" != "" ]]; then
            render_template "$f" "$dest_path" "$forwarding_secret" "$sport" "$sport"
          else
            render_template "$f" "$dest_path" "" "$sport" "$sport"
          fi
        else
          cp "$f" "$dest_path"
        fi
      done < <(find "$template_dir" -type f -print0)
    fi

    if [[ "$stype" == "paper" ]]; then
      write_eula "$sdir"
      if [[ -f "${sdir}/server.properties" ]]; then
        sed -i.bak "s/^server-port=.*/server-port=${sport}/" "${sdir}/server.properties"
        rm -f "${sdir}/server.properties.bak"
      fi
      if [[ "$forwarding_secret" != "" ]]; then
        echo "$forwarding_secret" > "${sdir}/forwarding.secret"
      fi
    fi

    log_ok "Configured ${sid} at ${sdir}"
  done < <(kit_servers "$kit_id")
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  apply_kit "${1:?kit_id}"
fi
