#Minecraft server properties
gamemode=survival
level-name=world
motd=Fabric Survival
pvp=true
difficulty=normal
max-players=100
online-mode=false
server-port=25567
white-list=false
spawn-protection=16
enable-command-block=false
